name: workflow
on: 
  workflow_dispatch:
  push:
   branches:
     - master
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.13.x' # you can use 1.12
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - name: Upgrades flutter 
      run: flutter upgrade --force
      working-directory: ./portfolio
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: ./portfolio
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./portfolio
    - name: Build Web
      run: flutter build web
      working-directory: ./portfolio
    - name: Insert PDF reader scripts
      run: |
        sed -i '43i\<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>\n<script type="text/javascript">\npdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";</script>\n</script>' portfolio/build/web/index.html
      working-directory: ./portfolio
    - name: Deploy
      run: |
        cd portfolio/build/web
        git init
        git config user.name  "GeddesWorks"
        git config user.email "collin.geddes@gmail.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/GeddesWorks/portfolio.git
        git checkout -b gh-pages
        echo "www.geddesworks.com" > CNAME
        git add .
        git commit -m "Updated docs"
        git push --force secure-origin gh-pages
